#! /bin/bash
# -----------------------------------------------------------------------
# List out installed packages that have no origin source in apt
# 
# PUPPET CONTROLED: pmodule_server_base
# -----------------------------------------------------------------------

COLUMNS=400 /usr/bin/dpkg -l | awk '/^ii/ {print $2}' | while read pkg
do
  /usr/bin/apt-cache policy $pkg |
	grep -A1 '^ \*\*\*' | grep -q '/var/lib/dpkg/status' && echo $pkg
done
